{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hjl.plugin",
    "module": "skin-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "skin-plugin-1.0.0.jar",
          "url": "skin-plugin-1.0.0.jar",
          "size": 1982,
          "sha512": "b26aefd6cbee62bf073edbdff32e56b252eb7f16ec91126553e6008cfe5edb32ab4d92af5735311d14865a9e68fe60a49db70f66977fdfe7d72059410e5df355",
          "sha256": "8ac68ff0a631e93795876dee78168c332a18e20ad811e79a248c04b1600bd662",
          "sha1": "b225ddc15af9b6b97c340975ded72afeede4bd07",
          "md5": "cf5975cbc279207bcf03ae0dfb853c50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "skin-plugin-1.0.0.jar",
          "url": "skin-plugin-1.0.0.jar",
          "size": 1982,
          "sha512": "b26aefd6cbee62bf073edbdff32e56b252eb7f16ec91126553e6008cfe5edb32ab4d92af5735311d14865a9e68fe60a49db70f66977fdfe7d72059410e5df355",
          "sha256": "8ac68ff0a631e93795876dee78168c332a18e20ad811e79a248c04b1600bd662",
          "sha1": "b225ddc15af9b6b97c340975ded72afeede4bd07",
          "md5": "cf5975cbc279207bcf03ae0dfb853c50"
        }
      ]
    }
  ]
}
