{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hjl.plugin",
    "module": "skin-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "skin-plugin-1.0.0.jar",
          "url": "skin-plugin-1.0.0.jar",
          "size": 5668,
          "sha512": "acf62c8616ab4aa9371a2bdcb9481eb56d2503d4ac804f07230f51d1a65b8120421406c779e6e9833bbe34a58affb550ca9bd2392cdbce7f84a417851df7838e",
          "sha256": "6d3d9e0990ddfc243fc97b4a84bb941485a9a961ff7839ed822c501fa22495bd",
          "sha1": "5f502467eadd66d81fccc024b886e5d23d8dd28d",
          "md5": "df4ad20b4d837cc8be6326241d8910fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "skin-plugin-1.0.0.jar",
          "url": "skin-plugin-1.0.0.jar",
          "size": 5668,
          "sha512": "acf62c8616ab4aa9371a2bdcb9481eb56d2503d4ac804f07230f51d1a65b8120421406c779e6e9833bbe34a58affb550ca9bd2392cdbce7f84a417851df7838e",
          "sha256": "6d3d9e0990ddfc243fc97b4a84bb941485a9a961ff7839ed822c501fa22495bd",
          "sha1": "5f502467eadd66d81fccc024b886e5d23d8dd28d",
          "md5": "df4ad20b4d837cc8be6326241d8910fc"
        }
      ]
    }
  ]
}
